zendtech/IbmiToolkit

- ToolkitApi/CW/DataDescription.php
- ToolkitApi/CW/DataDescriptionPcml.php
- ToolkitApi/DataArea.php
- ToolkitApi/DataQueue.php
- ToolkitApi/DateTimeApi.php
- ToolkitApi/JobLogs.php
- ToolkitApi/ListFromApi.php
- ToolkitApi/ObjectLists.php
- ToolkitApi/SpooledFiles.php
- ToolkitApi/SystemValues.php
- ToolkitApi/TmpUserSpace.php
- ToolkitApi/Toolkit.php
- ToolkitApi/ToolkitInterface.php
- ToolkitApi/UserSpace.php
- tests/ToolkitApiTest/ToolkitTest.php
Without an interface for the Toolkit class developers are forced to either implement their own interface or inject an implementation (Toolkit class) rather than an interface into their classes. Including ToolkitInterface in the package enables developers to "program to an interface, not an implementation."
> [WIP] Extract ToolkitInterface

- ToolkitApi/toolkit.ini
- Change library to QXMLSERV.
- Remove comment about test library XMLSERVICE because that will be seldom used nowadays
- Update comments for accuracy
Fixes #107
> Update toolkit.ini with IBM-shipped library name

- ToolkitApi/Toolkit.php
- tests/ToolkitApiTest/ToolkitTest.php
Prevent toolkit from misinterpreting invalid first parameter, especially if it is boolean false.
> type checking for databaseNameOrResource

- ToolkitApi/CW/cw.php
At some point, the require of cwclasses.php got dropped from cw.php. This commit adds it back so that the Compatibility Wrapper (CW) can work again. Fixes #117
> Add the require of cwclasses.php

- ToolkitApi/Toolkit.php
When validating $databaseNameOrResource, we need to allow for the PDO class. This change eliminates the error message "Failed to connect. databaseNameOrResource PDO::__set_state(array(
)) not valid"
> Check for PDO class

- ToolkitApi/Toolkit.php
Fixes #129 
The code's intent was to handle database errors, which return false, but because the code checked for !$outputXml, it interpreted an empty strings as an error, reporting "errors" that were merely empty output. This occurred, for example, when doing a disconnect() with the PDO transport. Now we check for false explicitly.
> Explicitly check for false in makeDbCall()

- ToolkitApi/TmpUserSpace.php
This was neglected when e14dea48ca530f575d7c2a9a28e2fd29ba4ffda7
refractored this class out into a separate file.
> TmpUserSpace inherits from UserSpace

- ToolkitApi/Toolkit.php
The glue comes before the pieces; the other way around was
deprecated in PHP 7.4.
> Fix argument order of implode

- ToolkitApi/Toolkit.php
- ToolkitApi/ToolkitInterface.php
- ToolkitApi/ToolkitServiceParameter.php
- ToolkitApi/ToolkitServiceXML.php
This isn't allowed by PHP anymore, and these seemingly were never
called omitting the optionals to the left of required. Changing
the order of the args would be breaking compat and setting a
default value would be semantically inappropriate on some.
The similator funcs/ctors that *did* have their required/optional
arguments in order weren't changed. This should go under some
review to make sure it doesn't break user code in avoidable ways,
but this is required going forward for PHP 8.
> Make supposedly optional arguments before required args required

- ToolkitApi/PdoSupp.php
Removed transaction that was causing errors binding XML parameter to the PDO execute() function.
Issue:  
https://github.com/zendtech/IbmiToolkit/issues/140
> Removed PDO transaction for execXMLStoredProcedure()

- ToolkitApi/SshSupp.php
- ToolkitApi/Toolkit.php
- ToolkitApi/ToolkitService.php
- ToolkitApi/autoload.php
- samples/ssh-transport.php
Uses PECL ssh2 (requires bleeding edge version to have `ssh2_send_eof`), requires `xmlservice-cli` on remote IBM i host.
This changes the API for transports slightly to pass information without having to use Toolkit-wide options, which seemed inappropriate to me. The API remains compatible with the old signature. This works for trivial things, but I don't know if this is the best solution.
Fixes #134
> WIP: SSH transport for Toolkit

- README.md
The board behind has been filled with off-topic materials before and now it is not accessible at all. Perhaps we should consider using GitHub Discussions feature instead?
> Update the information about discussions board

- ToolkitApi/Toolkit.php
When the Qshell exit code returns a nonzero value, the command has failed, even when Qshell provides no details on the error. The result of qshellCommand(), therefore, should be false.
> qshellCommand()=false when nonzero exit code

- ToolkitApi/CW/cw.php
Adopt a more reliable way to set 'localhost' as the default host if empty $host was specified in i5_connect(). Although the $host parameter of i5_connect() defaulted to 'localhost' in the argument list, this was not a reliable way to ensure 'localhost' for an empty host value. We saw this at a client who used ('', '', '', array(i5_libl...)) and got an error about an unknown host value.
> i5_connect(): default host to 'localhost'

- ToolkitApi/ToolkitService.php
With IDE's like Visual Studio Code there are PHP language server plugins like "PHP Intelephense" that offer IntelliSense and error checking for type hinting.  The @return type in the getInstance() docblock indicates "bool|null" and all variables assigned to this return type will assume a 'bool' value.
Instantiating the variable:
$conn = \ToolkitService::getInstance($db, $userOrI5NamingFlag='0', $password='', $transportType='pdo');
Using the variable will highlight an error detected with varaible "$conn":
$conn->setOptions(['stateless'=>true]);
Error message:
Expected type 'object'. Found 'bool|null'.
Changing the @return type to "Toolkit" removes the error syntax highlighting from the IDE, and correctly interprets/inspects the functions that the variable uses.
> Docbloc return type for ToolkitService::getInstance() incorrect

- ToolkitApi/PdoSupp.php
$result[0] could fail with "Undefined array key 0" if the Pdo default fetch mode was associative. Using the reset() function returns the first column, the equivalent of index 0 or whatever the associative key might be. There is only one column to retrieve, so this should always work.  Resolves issue #184.
> Don't assume numeric index

- ToolkitApi/ToolkitServiceXML.php
Proposal for solving:
bin2hex(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/zendtech/ibmitoolkit/ToolkitApi/ToolkitServiceXML.php on line 128
> Proposal for solving bin2hex deprecation message

- ToolkitApi/Odbcsupp.php
- ToolkitApi/Toolkit.php
**Summary of Changes**:
Updated validation to handle the `Odbc\Connection` and `Odbc\Result` return types introduced in PHP 8.4. For PHP 8.4 and above, checks are now made for `Odbc\Connection` (from `odbc_connect()`) and `Odbc\Result` (from `odbc_exec()`). Retained support for PHP 8.3 and earlier, which use resource-based return types.
**Why This Change**:
Ensures proper handling of ODBC connections and executions across PHP versions prior to 8.4, as well as 8.4 and above.
**Testing**:
Verified functionality on PHP 8.3 and 8.4 locally with successful results. The changes were tested primarily in the `connect()` function in `Odbcsupp.php` and the `__construct` method in `Toolkit.php`. Did not test the `executeQuery()` and `disconnect()` functions in `Odbcsupp.php`, as they are not used in …
> Update ODBC connection validation for PHP 8.4 compatibility

- ToolkitApi/Toolkit.php
- UNITTEST.md
- tests/config/db.config.php.dist
- tests/functional/ToolkitTest.php
**Description:**  
This PR introduces the ability to run unit tests using SQLite, which can be helpful when an IBM i system is not available. It also enables running the unit tests on pull requests across multiple PHP versions using GitHub Actions. Additionally, it addresses some compatibility issues with ODBC connections in PHP 8.4.
- **Improved ODBC connection handling** to support `\Odbc\Connection` and fix compatibility issues in PHP 8.4.  
- **Updated unit tests** to dynamically determine the DSN based on configuration and **added SQLite support** through the `mockDb2UsingSqlite` option for improved flexibility and maintainability.
I understand that these changes might not have been requested, so if they're not of interest or not aligned with the project's goals, I completely …
> Enable SQLite for Unit Testing & Improve ODBC Compatibility in PHP 8.4

- composer.json
I think this one is also relevant.
This pull request bumps the minimum required PHP version to 7.1 in the composer.json file. The reason for this change is that https://github.com/zendtech/IbmiToolkit/pull/218 commit introduced Nullable types and Class constant visibility modifiers, which are features available in PHP 7.1 and later versions.
By updating the minimum PHP version, we prevent potential installation issues for users who are still using older PHP versions. See also the release notes for PHP 7.1: https://www.php.net/releases/7_1_0.php
> Bump minimum PHP version to 7.1
